name = "factos_kurrentdb_erlang"
version = "1.0.0"

[dependencies]
factos = { path = "../.." }
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
kurrentdb = { path = "../../../kurrentdb" }
kurrentdb_erlang = { path = "../../../kurrentdb/backends/kurrentdb_erlang" }
youid = ">= 1.6.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
global_value = ">= 1.0.0 and < 2.0.0"
